import { fetchGitHubData } from "../../../../lib/github";
import { buildCityModel } from "../../../../lib/city";
import { geminiGenerate, hasGeminiKey } from "../../../../lib/gemini";

// AI "city inspector's report" — a short narrated walking tour of the
// skyline, generated by Google Gemini (free tier) when a GEMINI_API_KEY
// is configured.

export async function GET(request, { params }) {
  const { username } = await params;

  if (!/^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,38})$/.test(username)) {
    return Response.json({ error: "invalid_username" }, { status: 400 });
  }

  if (!hasGeminiKey()) {
    return Response.json({ error: "no_key" }, { status: 501 });
  }

  try {
    const data = await fetchGitHubData(username);
    if (data.notFound) {
      return Response.json({ error: "not_found" }, { status: 404 });
    }

    const city = buildCityModel(data);
    const facts = {
      login: data.user.login,
      name: data.user.name,
      bio: data.user.bio,
      accountAgeYears: city.analysis.accountAgeYears,
      towers: city.towerCount,
      totalContributions: city.totalContributions,
      totalStars: city.analysis.totalStars,
      currentStreak: city.currentStreak,
      longestStreak: city.analysis.longestStreak,
      bestDay: city.analysis.bestDay,
      busiestWeekday: city.analysis.busiestWeekday,
      momentumPct: city.momentum.pct,
      districts: city.analysis.districts,
      landmarks: city.landmarks.map((l) => ({
        name: l.name,
        stars: l.stars,
        description: l.description,
        language: l.language,
      })),
    };

    const system =
      "You are the City Inspector of Commit City — an app that renders a developer's GitHub profile as the New York skyline at night (one tower per repo, height from stars, windows lit by recent pushes). Write a short, atmospheric inspector's report in a warm NYC-noir tone: 3 short paragraphs, walking-tour style. Reference the real data (landmarks by name, districts, records). Be specific and charming, never snarky about quiet periods. End with one concrete, encouraging suggestion for the city's next development project. Plain text only, no markdown headers.";

    const user = `Here is the city data:\n${JSON.stringify(facts, null, 2)}`;

    const text = await geminiGenerate({ system, user, maxTokens: 1200 });
    return Response.json({ report: text });
  } catch (err) {
    if (err.message === "rate_limited") {
      return Response.json({ error: "rate_limited" }, { status: 429 });
    }
    return Response.json({ error: "unexpected" }, { status: 500 });
  }
}
