import { fetchGitHubData } from "../../../../lib/github";
import { buildCityModel } from "../../../../lib/city";

// AI "city inspector's report" — a short narrated walking tour of the
// skyline, generated by Claude when an ANTHROPIC_API_KEY is configured.

export async function GET(request, { params }) {
  const { username } = await params;

  if (!/^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,38})$/.test(username)) {
    return Response.json({ error: "invalid_username" }, { status: 400 });
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    return Response.json({ error: "no_key" }, { status: 501 });
  }

  try {
    const data = await fetchGitHubData(username);
    if (data.notFound) {
      return Response.json({ error: "not_found" }, { status: 404 });
    }

    const city = buildCityModel(data);
    const facts = {
      login: data.user.login,
      name: data.user.name,
      bio: data.user.bio,
      accountAgeYears: city.analysis.accountAgeYears,
      towers: city.towerCount,
      totalContributions: city.totalContributions,
      totalStars: city.analysis.totalStars,
      currentStreak: city.currentStreak,
      longestStreak: city.analysis.longestStreak,
      bestDay: city.analysis.bestDay,
      busiestWeekday: city.analysis.busiestWeekday,
      momentumPct: city.momentum.pct,
      districts: city.analysis.districts,
      landmarks: city.landmarks.map((l) => ({
        name: l.name,
        stars: l.stars,
        description: l.description,
        language: l.language,
      })),
    };

    const { default: Anthropic } = await import("@anthropic-ai/sdk");
    const client = new Anthropic();

    const response = await client.messages.create({
      model: "claude-opus-4-8",
      max_tokens: 1024,
      thinking: { type: "adaptive" },
      system:
        "You are the City Inspector of Commit City — an app that renders a developer's GitHub profile as the New York skyline at night (one tower per repo, height from stars, windows lit by recent pushes). Write a short, atmospheric inspector's report in a warm NYC-noir tone: 3 short paragraphs, walking-tour style. Reference the real data (landmarks by name, districts, records). Be specific and charming, never snarky about quiet periods. End with one concrete, encouraging suggestion for the city's next development project. Plain text only, no markdown headers.",
      messages: [
        {
          role: "user",
          content: `Here is the city data:\n${JSON.stringify(facts, null, 2)}`,
        },
      ],
    });

    const text = response.content.find((b) => b.type === "text")?.text;
    if (!text) return Response.json({ error: "unexpected" }, { status: 500 });

    return Response.json({ report: text });
  } catch (err) {
    if (err.message === "rate_limited") {
      return Response.json({ error: "rate_limited" }, { status: 429 });
    }
    return Response.json({ error: "unexpected" }, { status: 500 });
  }
}
